//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Labb1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WebShopGr7Entities : DbContext
    {
        public WebShopGr7Entities()
            : base("name=WebShopGr7Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<tbl_Attribute> tbl_Attribute { get; set; }
        public virtual DbSet<tbl_Audit> tbl_Audit { get; set; }
        public virtual DbSet<tbl_Brand> tbl_Brand { get; set; }
        public virtual DbSet<tbl_Carrier> tbl_Carrier { get; set; }
        public virtual DbSet<tbl_Category> tbl_Category { get; set; }
        public virtual DbSet<tbl_Order> tbl_Order { get; set; }
        public virtual DbSet<tbl_Order_Product_Attribute> tbl_Order_Product_Attribute { get; set; }
        public virtual DbSet<tbl_Page> tbl_Page { get; set; }
        public virtual DbSet<tbl_Payment> tbl_Payment { get; set; }
        public virtual DbSet<tbl_Product> tbl_Product { get; set; }
        public virtual DbSet<tbl_Product_Attribute> tbl_Product_Attribute { get; set; }
        public virtual DbSet<tbl_User> tbl_User { get; set; }
    }
}
