//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Labb1
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Order()
        {
            this.tbl_Order_Product_Attribute = new HashSet<tbl_Order_Product_Attribute>();
        }
    
        public int ID { get; set; }
        public int UserID { get; set; }
        public int CarrierID { get; set; }
        public int PaymentID { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual tbl_Carrier tbl_Carrier { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Order_Product_Attribute> tbl_Order_Product_Attribute { get; set; }
        public virtual tbl_Payment tbl_Payment { get; set; }
        public virtual tbl_User tbl_User { get; set; }
    }
}
