//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Labb1
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Product_Attribute
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Product_Attribute()
        {
            this.tbl_Order_Product_Attribute = new HashSet<tbl_Order_Product_Attribute>();
        }
    
        public int ID { get; set; }
        public Nullable<int> AttributeID1 { get; set; }
        public Nullable<int> AttributeID2 { get; set; }
        public Nullable<int> AttributeID3 { get; set; }
        public Nullable<int> AttributeID4 { get; set; }
        public int ProductID { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<decimal> PriceB2B { get; set; }
        public decimal PriceB2C { get; set; }
        public string ArticleNumber { get; set; }
        public System.DateTime DateMade { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Order_Product_Attribute> tbl_Order_Product_Attribute { get; set; }
    }
}
