//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Labb1
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Order_Product_Attribute
    {
        public int OrderID { get; set; }
        public int ProductAttributeID { get; set; }
        public int Quantity { get; set; }
    
        public virtual tbl_Order tbl_Order { get; set; }
        public virtual tbl_Product_Attribute tbl_Product_Attribute { get; set; }
    }
}
