//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Labb1
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Product
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int BrandID { get; set; }
        public int CategoryID { get; set; }
        public string ImgUrl { get; set; }
        public Nullable<System.DateTime> DateMade { get; set; }
    
        public virtual tbl_Brand tbl_Brand { get; set; }
        public virtual tbl_Category tbl_Category { get; set; }
    }
}
